apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongodb
        image: mongo:8.0
        ports:
        - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-service    // This is the service name that will be used in the application
spec:
  selector:      
    app: mongo           // This should match the label in the deployment
  ports:
    - protocol: TCP
      port: 27017        // This is the port that will be exposed
      targetPort: 27017    // This should match the container port in the deployment

