apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: nanajanashia/k8s-demo-app:v1.0    // This is the image that will be used for the deployment
        ports:
        - containerPort: 3000  // This is the port that the application will listen on

---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service    // This is the service name that will be used in the application
spec:
  selector:      
    app: webapp           // This should match the label in the deployment
  ports:
    - protocol: TCP
      port: 3000        // This is the port that will be exposed
      targetPort: 3000    // This should match the container port in the deployment

